"""Optional adapter for the real doomfly MaleCNS graph.

The graph is intentionally not bundled with gnat: the upstream dataset is
large and has its own provenance/download procedure.  When a graph path is
provided, this adapter loads doomfly's CSR/LIF engine instead of the compact
NumPy demo circuit.  Without that path the viewer must remain visibly marked
as a demo; it must never silently invent a connectome.
"""

from __future__ import annotations

import importlib
import json
import math
import sys
from pathlib import Path
from typing import Any, Mapping, Sequence

import numpy as np
from numpy.typing import NDArray

from gnat.brain.protocol import BrainStepResult


class DoomflyBackendError(RuntimeError):
    """Raised when the optional upstream doomfly engine cannot be loaded."""


class DoomflyBrain:
    """Run the upstream MaleCNS graph through its audited doomfly engine.

    ``graph_path`` must point to doomfly's generated ``graph.npz``.  The
    optional ``doomfly_root`` is the checkout containing the upstream
    ``doom/`` package.  The adapter prefers the native kernel when available
    and otherwise uses the upstream NumPy/Numba reference engine.
    """

    def __init__(
        self,
        graph_path: str | Path,
        *,
        doomfly_root: str | Path | None = None,
        readouts: Sequence[Mapping[str, Any]] = (),
        prefer_native: bool = True,
    ) -> None:
        self.graph_path = Path(graph_path).expanduser().resolve()
        if not self.graph_path.is_file():
            raise FileNotFoundError(
                "MaleCNS graph.npz is missing: "
                f"{self.graph_path}. Generate it with doomfly's documented "
                "connectome download/import pipeline before enabling this backend."
            )
        if doomfly_root is not None:
            root = str(Path(doomfly_root).expanduser().resolve())
            if root not in sys.path:
                sys.path.insert(0, root)

        self._engine, self.engine_name = self._load_engine(
            self.graph_path, prefer_native=prefer_native
        )
        self._readouts = self._validate_readouts(readouts, self._engine.n)
        controls_class = self._load_controls_class()
        self._controls = (
            controls_class(self._readouts, mode="bci") if self._readouts else None
        )
        self._total_spikes = 0
        self._last_counts = np.zeros(self._engine.n, dtype=np.int32)
        self._group_indices = {
            name: np.flatnonzero(self._engine.superclass == name)
            for name in (
                "visual_projection",
                "ol_intrinsic",
                "cb_intrinsic",
                "descending_neuron",
            )
            if hasattr(self._engine, "superclass")
        }

    @classmethod
    def from_manifest(
        cls,
        graph_path: str | Path,
        manifest_path: str | Path,
        *,
        doomfly_root: str | Path | None = None,
        prefer_native: bool = True,
    ) -> "DoomflyBrain":
        """Construct an adapter using readout indices recorded by doomfly."""

        manifest_file = Path(manifest_path).expanduser().resolve()
        if not manifest_file.is_file():
            raise FileNotFoundError(
                "Doomfly manifest.json was not found: "
                f"{manifest_file}. Replace the example /path/to/manifest.json "
                "with the real path generated by doomfly."
            )
        with manifest_file.open(encoding="utf-8") as stream:
            manifest = json.load(stream)
        readouts = manifest.get("readouts")
        if not isinstance(readouts, list):
            raise DoomflyBackendError("doomfly manifest must contain a readouts list")
        return cls(
            graph_path,
            doomfly_root=doomfly_root,
            readouts=readouts,
            prefer_native=prefer_native,
        )

    @property
    def input_size(self) -> int:
        """Number of retina neurons required by the loaded graph."""

        return int(len(self._engine.retina))

    @property
    def neuron_count(self) -> int:
        return int(self._engine.n)

    @property
    def edge_count(self) -> int:
        return int(len(self._engine.post))

    @property
    def engine_source_path(self) -> Path | None:
        """Return the loaded engine module path when it is available locally."""

        module_name = type(self._engine).__module__
        try:
            module = importlib.import_module(module_name)
        except (ImportError, ModuleNotFoundError):
            return None
        module_path = getattr(module, "__file__", None)
        if not isinstance(module_path, str):
            return None
        path = Path(module_path).expanduser().resolve()
        return path if path.is_file() else None

    @property
    def snapshot(self) -> dict[str, object]:
        """Return compact activity data for the browser inspector."""

        retina = self._downsample(self._engine.luminance, 32)
        visual = self._group_activity(
            self._group_indices.get("visual_projection", np.empty(0, dtype=int))
        )
        optic = self._group_activity(
            self._group_indices.get("ol_intrinsic", np.empty(0, dtype=int))
        )
        central = self._group_activity(
            self._group_indices.get("cb_intrinsic", np.empty(0, dtype=int))
        )
        motor = self._group_activity(
            self._group_indices.get("descending_neuron", np.empty(0, dtype=int))
        )
        return {
            "retina": retina,
            "optic_lobe": visual + optic,
            "central_complex": central,
            "motor": motor,
            "transmission": [
                float(np.mean(retina)) if retina else 0.0,
                float(np.mean(visual + optic)) if visual or optic else 0.0,
                float(np.mean(central)) if central else 0.0,
                float(np.mean(motor)) if motor else 0.0,
            ],
            "latency_ms": [0.0, 1.8, 3.6, 5.4],
            "time_ms": float(getattr(self._engine, "sim_ms", 0.0)),
            "total_spikes": self._total_spikes,
            "backend": "doomfly-malecns",
            "engine": self.engine_name,
            "neuron_count": self.neuron_count,
            "edge_count": self.edge_count,
        }

    def step(
        self,
        retina_luminance: NDArray[np.floating],
        duration_ms: float,
    ) -> BrainStepResult:
        """Advance the loaded whole-connectome engine for one interval."""

        retina = np.asarray(retina_luminance, dtype=np.float32)
        if retina.shape != (self.input_size,):
            raise ValueError(f"retina_luminance must have shape ({self.input_size},)")
        if not np.all(np.isfinite(retina)):
            raise ValueError("retina_luminance must contain only finite values")
        if np.any(retina < 0.0) or np.any(retina > 1.0):
            raise ValueError("retina_luminance must be normalized to [0, 1]")
        if not math.isfinite(duration_ms) or duration_ms <= 0:
            raise ValueError("duration_ms must be positive and finite")

        counts, _wall_seconds = self._engine.step(retina, duration_ms)
        self._last_counts = np.asarray(counts, dtype=np.int32)
        spikes = int(self._last_counts.sum())
        self._total_spikes += spikes
        motor_output: tuple[float, ...] = ()
        readout_counts: dict[str, int] = {}
        if self._controls is not None:
            controls = self._controls.decode(
                self._last_counts, duration_ms / 1000.0
            )
            for readout in self._readouts:
                label = str(readout["type"])
                if readout.get("side"):
                    label += f"_{readout['side']}"
                readout_counts[label] = readout_counts.get(label, 0) + int(
                    self._last_counts[int(readout["index"])]
                )
            # This is the explicit BCI interface from doomfly, normalized for
            # gnat's actuator boundary.  It is not a claim about natural fly
            # joint commands.
            motor_output = (
                float(np.clip(controls["forward"] / 20.0, -1.0, 1.0)),
                float(np.clip(controls["turn"] / 6.0, -1.0, 1.0)),
            )
        return BrainStepResult(
            duration_ms=duration_ms,
            total_spikes=spikes,
            readouts=readout_counts,
            motor_output=motor_output,
        )

    def reset(self) -> None:
        """Reset dynamic state while retaining the loaded connectome."""

        self._engine.cursor = 0
        self._engine.v.fill(-52.0)
        self._engine.g.fill(0.0)
        self._engine.drive.fill(0.0)
        self._engine.refractory.fill(0)
        self._engine.queue.fill(0)
        self._engine.queue_count.fill(0)
        self._engine.counts.fill(0)
        self._engine.luminance.fill(0.0)
        self._engine.active_flag.fill(0)
        initial = np.unique(
            np.r_[self._engine.retina, self._engine.lamina, self._engine.sugar]
        )
        self._engine.active.fill(0)
        self._engine.active[: len(initial)] = initial
        self._engine.active_flag[initial] = 1
        self._engine.nactive[0] = len(initial)
        self._engine.total_spikes = 0
        self._engine.sim_ms = 0.0
        self._last_counts.fill(0)
        self._total_spikes = 0

    @staticmethod
    def _load_engine(graph_path: Path, *, prefer_native: bool) -> tuple[Any, str]:
        try:
            if prefer_native:
                native = importlib.import_module("doom.native")
                return native.NativeBrain(str(graph_path)), "native"
        except (ImportError, OSError, RuntimeError, ModuleNotFoundError):
            pass
        try:
            engine = importlib.import_module("doom.engine")
            return engine.Brain(str(graph_path)), "numba-reference"
        except (ImportError, OSError, RuntimeError, ModuleNotFoundError) as error:
            raise DoomflyBackendError(
                "doomfly engine is unavailable; provide doomfly_root and its "
                "runtime dependencies (NumPy/Numba)."
            ) from error

    @staticmethod
    def _load_controls_class() -> Any:
        try:
            return importlib.import_module("doom.engine").NeuralControls
        except (ImportError, ModuleNotFoundError) as error:
            raise DoomflyBackendError(
                "doomfly.engine.NeuralControls is required for readout decoding"
            ) from error

    @staticmethod
    def _validate_readouts(
        readouts: Sequence[Mapping[str, Any]], neuron_count: int
    ) -> tuple[dict[str, Any], ...]:
        normalized: list[dict[str, Any]] = []
        for readout in readouts:
            if not isinstance(readout, Mapping):
                raise DoomflyBackendError("every readout must be an object")
            index = readout.get("index")
            name = readout.get("type")
            if isinstance(index, bool) or not isinstance(index, (int, np.integer)):
                raise DoomflyBackendError("readout index must be an integer")
            if not isinstance(name, str) or not name:
                raise DoomflyBackendError("readout type must be a non-empty string")
            if index < 0 or index >= neuron_count:
                raise DoomflyBackendError("readout index is outside the graph")
            normalized.append(
                {
                    "index": int(index),
                    "id": str(readout.get("id", index)),
                    "type": name,
                    "side": str(readout.get("side", "")),
                }
            )
        return tuple(normalized)

    def _group_activity(self, indices: NDArray[np.integer]) -> list[float]:
        if len(indices) == 0:
            return []
        values = self._last_counts[indices]
        return self._downsample(values, 32)

    @staticmethod
    def _downsample(values: NDArray[np.floating] | NDArray[np.integer], size: int) -> list[float]:
        array = np.asarray(values, dtype=np.float32)
        if array.size == 0:
            return []
        return [float(np.mean(chunk)) for chunk in np.array_split(array, min(size, array.size))]
